[tool.ruff]
target-version = "py311"
line-length = 88
fix = true

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "C4", "UP", "ARG", "SIM", "TCH", "DTZ", "ERA", "PTH", "RUF", "ANN", "ASYNC", "S", "BLE"]
ignore = ["E501", "S101", "ANN101", "ANN102", "ANN401"]

[tool.mypy]
python_version = "3.11"
strict = true
disallow_any_explicit = true
